import {Footer,Header,base,whatsapp} from './site';

const pillars=[
  {title:'Media Production',copy:'Phone-first filming and production for weddings, events, dramas, interviews, creator content, adverts and business stories.',href:'/production/'},
  {title:'AI Studio',copy:'Selective AI assistance for scripting, storyboards, graphics, subtitles, voice, music, visual effects, editing support and campaign assets.',href:'/ai-studio/'},
  {title:'Academy',copy:'Practical AI and media training for creators, workers, entrepreneurs, schools and communities.',href:'/academy/'}
];
const formats=['Weddings & events','Short films & local drama','Interviews & profiles','Business adverts','Creator videos','Training content','Photography & visual stories','Social media campaigns'];
const ai=['Script & concept development','Storyboards and shot planning','Subtitles and transcription','Graphics and promotional artwork','Voice and audio enhancement','Music ideation','Editing assistance','VFX experimentation','Content repurposing','Campaign support'];

export default function HomePage(){return <main><Header/>
  <section className="hero" id="top"><div className="heroCopy"><p className="eyebrow">TALUNZA MEDIA · ZIMBABWE</p><h1>Real stories. Better production. Smarter tools.</h1><p className="lede">We combine practical filming, editing and storytelling with selective AI tools to help people and organisations create work that looks stronger, communicates clearly and travels further.</p><div className="actions"><a className="primary" href={whatsapp}>Discuss your project</a><a className="secondary" href={`${base}/services/`}>Explore services</a></div><p className="micro">Not “AI-only”. We shoot real people, real places and real work — then use technology where it adds value.</p></div><div className="heroPanel"><div className="frame"><strong>Capture</strong><small>Real-world phone-first production</small></div><div className="frame"><strong>Craft</strong><small>Edit, design, sound and story</small></div><div className="frame"><strong>Amplify</strong><small>AI-assisted finishing and distribution</small></div></div></section>

  <section className="section"><p className="eyebrow dark">THREE CONNECTED PILLARS</p><h2>Production, intelligence and skills in one creative system.</h2><div className="cards">{pillars.map(p=><article className="card" key={p.title}><h3>{p.title}</h3><p>{p.copy}</p><a className="textLink" href={`${base}${p.href}`}>Explore {p.title} →</a></article>)}</div></section>

  <section className="section split"><div><p className="eyebrow dark">WHAT WE MAKE</p><h2>Built for real audiences and real channels.</h2><p className="copy">The work may end up on WhatsApp Status, YouTube, TikTok, Instagram, a website, a projector, a classroom screen or a client presentation. We plan for the destination from the start.</p></div><div className="chips">{formats.map(x=><span key={x}>{x}</span>)}</div></section>

  <section className="section darkSection"><p className="eyebrow">AI STUDIO</p><h2>AI is part of the toolkit — not the whole identity.</h2><p className="copy light">We use AI selectively to reduce friction, explore ideas faster and raise production quality while keeping human judgement and the purpose of the project in control.</p><div className="chips darkChips">{ai.map(x=><span key={x}>{x}</span>)}</div><div className="actions"><a className="secondary" href={`${base}/ai-studio/`}>See the AI Studio</a></div></section>

  <section className="section"><p className="eyebrow dark">TALUNZA ACADEMY</p><h2>Learn tools by making useful things.</h2><div className="academyGrid"><article><h3>AI for everyday work</h3><p>Prompting, research, writing, planning, automation and practical assistants.</p></article><article><h3>Phone media production</h3><p>Framing, sound, lighting, interviews, shot planning, editing and publishing.</p></article><article><h3>Creator & business workflows</h3><p>Turn one idea or shoot into multiple useful formats for WhatsApp, social media, websites and campaigns.</p></article><article><h3>Earn with new skills</h3><p>Training tied to practical services, portfolio building and real commercial opportunities.</p></article></div><div className="actions"><a className="primary" href={`${base}/academy/`}>Explore the Academy</a></div></section>

  <section className="section process"><p className="eyebrow dark">HOW PROJECTS START</p><h2>Tell us what you want people to see, feel or understand.</h2><div className="steps"><div><b>1</b><h3>Brief</h3><p>Goal, audience, location, deadline and available material.</p></div><div><b>2</b><h3>Plan</h3><p>Concept, shot list, script, crew needs and delivery format.</p></div><div><b>3</b><h3>Produce</h3><p>Capture, edit, enhance and review.</p></div><div><b>4</b><h3>Deliver</h3><p>Final files prepared for the channels that matter.</p></div></div></section>

  <section className="section"><div className="split"><div><p className="eyebrow dark">WHY THIS MODEL</p><h2>Small setup. Serious thinking.</h2></div><div><p className="copy">A disciplined phone-first workflow can move faster and cost less than a traditional production while still producing credible work. When a project genuinely needs more equipment, crew or specialist capability, we scope that deliberately instead of pretending one setup fits everything.</p><a className="textLink" href={`${base}/about/`}>How Talunza Media works →</a></div></div></section>

  <section className="cta"><p className="eyebrow">START WITH THE IDEA</p><h2>Wedding, advert, drama, interview, training idea or AI project?</h2><p>Send the idea first. We will help shape the right production approach before quoting.</p><div className="actions"><a className="primary" href={whatsapp}>WhatsApp Talunza Media</a><a className="secondary" href={`${base}/contact/`}>Contact details</a></div></section><Footer/>
</main>}
